### ISSUE TITLE
List Devices (EDSDK) - Refresh error

### ISSUE THREAD

**Issue by Hapboy** [elliotwoods/VVVV.Packs.Image#44] opened 2013-12-12 23:07 UTC
List Devices (EDSDK)
Don't working Refresh Pin
When patch start all work nice, when bang Refresh status printing

ERROR : Internal Error.
Failed to open session.

**Comment by elliotwoods** [comment] 2013-12-18 07:32
Please check issue at #32 
Closing this one as duplicate.

**Comment by elliotwoods** [comment] 2013-12-18 07:33
thanks for reporting! 
the issue is currently to do with the underlying API not being sensible w.r.t. refereshing devices
i've been trying some workarounds, but still issues so far.

**Closed as completed by elliotwoods** 2013-12-18 07:32 UTC
